[package]
name = "ProSint"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.8", features = ["cargo"] }
colored = "2.1.0"
regex = "1.10.5"
reqwest = "0.12.5"
tokio = { version = "1.38.0", features = ["full"] }
